export const AUDIT_ARTIFACT_PATHS = Object.freeze({
  summary: "data/summary.json",
  pages: "data/pages.json",
  pagesJsonl: "data/pages.jsonl",
  pageMetrics: "data/page-metrics.json",
  pageMetricsJsonl: "data/page-metrics.jsonl",
  pageInsights: "data/page-insights.json",
  pageInsightsJsonl: "data/page-insights.jsonl",
  siteMetrics: "data/site-metrics.json",
  edges: "evidence/edges.json",
  edgesJsonl: "evidence/edges.jsonl",
  findings: "evidence/findings.json",
  findingsJsonl: "evidence/findings.jsonl",
  renderAudits: "evidence/render-audits.json",
  renderAuditsJsonl: "evidence/render-audits.jsonl",
  ruleEvaluations: "rules/evaluations.json",
  ruleEvaluationsJsonl: "rules/evaluations.jsonl",
  ruleCatalog: "rules/catalog.json",
  ruleCatalogJsonl: "rules/catalog.jsonl",
  report: "report.md",
  markdownOverview: "markdown/overview.md",
  markdownStructure: "markdown/structure.md",
  markdownRendering: "markdown/rendering.md",
  markdownIssueIndex: "markdown/issues/index.md",
  markdownPageIndex: "markdown/pages/index.md",
  markdownGlossary: "markdown/glossary.md",
  markdownAgentGuide: "markdown/agent-guide.md",
} as const);

export const LEGACY_AUDIT_ARTIFACT_PATHS = Object.freeze({
  summary: "summary.json",
  pages: "pages.json",
  pageMetrics: "page-metrics.json",
  pageInsights: "page-insights.json",
  siteMetrics: "site-metrics.json",
  edges: "edges.json",
  findings: "findings.json",
  renderAudits: "render-audits.json",
  ruleEvaluations: "rules.json",
  ruleCatalog: "rule-catalog.json",
} as const);

